'use client';
import {useEffect,useState} from 'react';
export default function Admin(){
 const [d,setD]=useState(null),[key,setKey]=useState(''),[adminId,setAdminId]=useState(''),[conv,setConv]=useState(''),[text,setText]=useState(''),[importText,setImportText]=useState(''),[result,setResult]=useState('');
 const load=()=>fetch('/api/dashboard').then(r=>r.json()).then(setD); useEffect(()=>{load()},[]);
 async function send(){const r=await fetch('/api/admin/reply',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key},body:JSON.stringify({conversation_id:conv,admin_id:adminId,text})});setResult(JSON.stringify(await r.json(),null,2));load();}
 async function imp(){const r=await fetch('/api/admin/import',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key},body:JSON.stringify({text:importText})});setResult(JSON.stringify(await r.json(),null,2));load();}
 return <div className="shell"><aside className="side"><div className="brand">QC<span>Admin</span></div><nav className="nav"><a href="/">Dashboard</a><a className="active" href="/admin">Admin Console</a><a href="/docs">Setup Docs</a></nav></aside><main className="main"><h1>Admin Console</h1><p className="muted">ใช้หน้านี้ตอบลูกค้าผ่าน LINE Push API เพื่อให้ระบบวัด SLA และ QC ได้ครบ ถ้าไปตอบใน LINE OA Manager โดยตรง LINE ไม่ส่งข้อความแอดมินกลับมาที่ webhook — ตรงนี้แหละกับดักตัวใหญ่</p><div className="cols"><div className="card"><h2>1) Import Admin จาก Manage permissions</h2><p className="muted">คัดลอกชื่อ Member จาก LINE OA Manage permissions มาวาง ระบบจะเก็บเฉพาะชื่อขึ้นต้น PK แม้มี emoji ปน</p><input placeholder="ADMIN_API_KEY" value={key} onChange={e=>setKey(e.target.value)}/><textarea rows="8" placeholder={'PK Golf 🚀\nPK May 🌟\nCS John'} value={importText} onChange={e=>setImportText(e.target.value)}/><button onClick={imp}>Import PK Admin</button></div><div className="card"><h2>2) Reply Customer</h2><select value={adminId} onChange={e=>setAdminId(e.target.value)}><option value="">เลือก Admin</option>{(d?.ranking||[]).map(a=><option key={a.id} value={a.id}>{a.member_name}</option>)}</select><select value={conv} onChange={e=>setConv(e.target.value)}><option value="">เลือก Case</option>{(d?.openCases||[]).map(c=><option key={c.id} value={c.id}>{(c.display_name||c.line_user_id)+' | '+c.message_text?.slice(0,40)}</option>)}</select><textarea rows="8" placeholder="ข้อความตอบลูกค้า" value={text} onChange={e=>setText(e.target.value)}/><button onClick={send}>Send + QC Score</button></div></div><pre className="card" style={{whiteSpace:'pre-wrap',marginTop:16}}>{result}</pre></main></div>
}
