'use client';
import { useEffect, useState } from 'react';
function fmtSec(s){s=Number(s||0); if(s<60)return `${s}s`; return `${Math.floor(s/60)}m ${s%60}s`}
function scoreClass(v){return v>=85?'good':v>=70?'warn':'bad'}
export default function Dashboard(){
 const [d,setD]=useState(null);
 useEffect(()=>{fetch('/api/dashboard').then(r=>r.json()).then(setD); const t=setInterval(()=>fetch('/api/dashboard').then(r=>r.json()).then(setD),15000); return()=>clearInterval(t)},[]);
 const k=d?.kpi||{};
 return <div className="shell"><aside className="side"><div className="brand">QC<span>Admin</span></div><nav className="nav"><a className="active" href="/">Dashboard</a><a href="/admin">Admin Console</a><a href="/docs">Setup Docs</a></nav></aside><main className="main"><div className="top"><div><h1>LINE OA Quality Dashboard</h1><div className="muted">ตรวจความเร็ว ความถูกต้อง น้ำเสียง และคะแนนแอดมินแบบ near real-time</div></div><div className="badge">Production Ready v1</div></div><section className="grid kpis"><K title="ลูกค้าแอดไลน์" v={k.customers||0}/><K title="สมัครผ่าน" v={k.registered_pass||0}/><K title="KYC ผ่าน" v={k.kyc_pass||0}/><K title="ยอดเติม" v={Number(k.deposit_total||0).toLocaleString()}/><K title="ตอบเฉลี่ย" v={fmtSec(k.avg_response_sec)}/><K title="คะแนนเฉลี่ย" v={k.avg_score||0}/></section><section className="grid split"><div className="card"><h2>Ranking Admin</h2><table className="table"><thead><tr><th>#</th><th>Admin</th><th>Cases</th><th>Avg Score</th><th>Avg Response</th></tr></thead><tbody>{(d?.ranking||[]).map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.member_name}</td><td>{r.cases}</td><td className={'score '+scoreClass(r.avg_score)}>{r.avg_score}</td><td>{fmtSec(r.avg_response_sec)}</td></tr>)}</tbody></table></div><div className="card"><h2>Promotion Performance</h2><table className="table"><thead><tr><th>Promo</th><th>ลูกค้า</th><th>ยอดเติม</th></tr></thead><tbody>{(d?.promos||[]).map((p,i)=><tr key={i}><td>{p.promotion_code}</td><td>{p.customer_count}</td><td>{Number(p.total_amount||0).toLocaleString()}</td></tr>)}</tbody></table></div></section><section className="card" style={{marginTop:16}}><h2>Open Cases</h2>{(d?.openCases||[]).map(c=><div className="case" key={c.id}><b>{c.display_name||c.line_user_id}</b><div className="muted">{c.id}</div><p>{c.message_text}</p></div>)}</section></main></div>
}
function K({title,v}){return <div className="card"><div className="kpi-title">{title}</div><div className="kpi-value">{v}</div></div>}
